### ISSUE TITLE
RCLONE_REFRESH_ON_MOUNT

### ISSUE THREAD

**Issue by seertenedos** [wiserain/docker-rclone#12]
Any chance you could provide some examples for this?
I am basically wanting to refresh the filelist at startup in a similar way to the below command does it
/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 127.0.0.1:5574 _async=true
but i have been unsable to workout how to correctly use the ENV variable above to correctly trigger a command like the one above for the whole mount,

I have tried / and . but both result in 
2022/05/05 12:13:13 REFRES: >>> refreshing "."
2022/05/05 12:13:16 REFRES: ".": file does not exist

Since rcloen does not keep the filelist over restarts this would allow it to use fastlane to quickly cache the remote filesystem structure and reduce the number of overall calls need for when an app then scans the filesystem.  This is useful for remote filesystems that provide changes to the filesystem structure as updates

**Comment by wiserain** [comment]
You can set a list of dirs, separated by bar `|`, to `RCLONE_REFRESH_ON_MOUNT`. For example, `RCLONE_REFRESH_ON_MOUNT=video|photo|docs`. Then, a built-in script parses dirs and calls multiple executions of `rclone rc vfs/refresh recursive=true dir=dir` synchronously.

However, it is not intended or designed for refreshing all sub-objects under the root of rclone remote to avoid wasting api quotas. You should use multiple sub-dirs as many as you want at this moment.

You may not be interested, but it has the same usage for `RCLONE_REFRESH_DIRS*` which will be triggered by `RCLONE_REFRESH_CRON*` having a same suffix `*` with `RCLONE_REFRESH_DIRS*`.

**Comment by seertenedos** [comment]
Can an option be added to refresh the whole drive on mount? It does not
waste API calls in fact it is the opposite as if you have things that scan
the content of the drive the will trigger a call per folder instead of one
to get many. I am using the VFS cache so the idea is to get the filesystem
structure in cache and then updates are picked up to filesystem by polling
change vs checking whole structure

**Comment by seertenedos** [comment]
To be clear I need to do all subfolders of the root and there can be
hundreds which I can't know till I scan anyway so most efficient to tell it
to load the whole drive structure to cache.

**Comment by wiserain** [comment]
Please find the feature here. 2fbe2d2b05b0409413ea77350d52dc9c95d82944 You can pass `.` or `/` to refresh all subs.

**Comment by seertenedos** [comment]
Got it, thanks!

**Comment by seertenedos** [comment]
This is working well so closing the issue
