### ISSUE TITLE
mergerfs ignoring defined PUID & PGID

### ISSUE THREAD

**Issue by nosliwkered** [wiserain/docker-rclone#2]
When using the mergerfs option, it ignores user-provided PUID & PGID environment variables.

Using the following:
```
environment:
  - PUID=1000
  - PGID=1000
volumes:
  - ${USERDIR}/test-rclone:/cloud:shared
  - ${USERDIR}/test-local:/local:shared
  - ${USERDIR}/test-merged:/data:shared
```
Creates the following output folder permissions:
```
drwxr-xr-x  2 root     root     4.0K May  6 15:14 test-local
drwxr-xr-x  2 user     user     4.0K May  6 15:14 test-merged
drwxr-xr-x  2 user     user     4.0K May  6 15:14 test-rclone
```

My current workaround is to create the local folder with user permissions before starting the container, but this is not ideal for portability reasons.

**Comment by wiserain** [comment]
I got remembered!

It's designed for the case that user-provided `/local` folder is not empty and sometime even contains huge amount of files so that might cause inefficiency in every container initialization step.

It is not based on a concrete fact though. How do you thinks?

**Comment by nosliwkered** [comment]
I think I'm tracking what you're concerned about, but I don't believe you should be worried. Docker volumes are persistent storage, so anything written by the container to `/local` will remain in `/local/dir/to/be/merged/with` when the container stops or is removed. If `/local/dir/to/be/merged/with` already exists when the container is started, then docker doesn't have to take any actions against the folder itself and successfully maps it and its existing data to the container's `/local`.

This issue I'm seeing is specific to the folder permissions associated with `/local/dir/to/be/merged/with` when it _doesn't_ already exist. For testing purposes, I'm using `/home/user/test-local`.  If `/home/user/test-local` doesn't already exist, the container creates it, but always using the default `PUID:-911` & `PGID:-911` and not the user-defined values in `docker-compose.yml`. This results in `/home/user/test-local` being created and successfully mapped to the container's `/local`, but `user` or any services running as `user` cannot write to it or to `/home/user/test-merged`, because it's ultimately still trying to write to `/home/user/test-local`.

Example:
```
user@hostname:~$ ls -l |grep test
drwxr-xr-x  2 root     root     4096 May  7 04:12 test-local
drwxr-xr-x  1 user     user        0 May  7 04:14 test-merged
drwxrwxr-x  1 user     user        0 May  7 04:14 test-rclone
user@hostname:~$ touch test-local/testfile
touch: cannot touch 'test-local/testeroo': Permission denied
user@hostname:~$ touch test-merged/testfile
touch: cannot touch 'test-merged/testeroo': Permission denied
user@hostname:~$ touch test-rclone/testfile
user@hostname:~$
```

**Comment by wiserain** [comment]
A test image is pushed. Would you mind testing it? You can try with `wiserain/rclone:testing` or `ghcr.io/wiserain/rclone:testing`. Thanks.

**Comment by nosliwkered** [comment]
Just tested it with both an existing local folder and non-existant one and it works well in either case! Great work!
